version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: video_downloader_bot
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - LOG_CHANNEL_ID=${LOG_CHANNEL_ID}
      - PORT=8080
    volumes:
      # حفظ البيانات بين إعادة التشغيل
      - ./stats.json:/app/stats.json
      - ./user_languages.json:/app/user_languages.json
      - downloads:/tmp/downloads
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  downloads:
